accounts/urls.py
"""
file: accounts/urls.py
author: lkmhaqer
"""
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
  path('detail', views.user_detail, name='user_detail'),
  path('register', views.user_registration, name='user_registration'),
  path(
    'register/<uuid:invite_token>',
    views.user_registration,
    name='invite_registration'
  ),
  path(
    'add_minecraft_user',
    views.add_minecraft_user,
    name='add_minecraft_user'
  ),
]

diamondserv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('', include('wrangler.urls')),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('admin/', admin.site.urls),
]

wrangler/urls.py
"""
file: wrangler/urls.py
author: lkmhaqer
"""
from django.urls import path

from . import views


app_name = 'wrangler'
urlpatterns = [
  path('', views.index, name='index'),
  path('page/<slug:template>', views.page, name='page'),
  path('status/', views.status, name='status'),
  path('status/<str:username>', views.status, name='user_status'),
  path(
    'server/create',
    views.server_create,
    name='server_create'
  ),
  path(
    'server/<slug:server_name>/delete',
    views.server_delete,
    name='server_delete'
  ),
  path(
    'server/<slug:server_name>/restart',
    views.server_restart,
    name='server_restart'
  ),
  path(
    'server/<slug:server_name>/detail',
    views.server_detail,
    name='server_detail'
  ),
]

wrangler/models.py
"""
file: wrangler/models.py
author: lkmhaqer
"""
from django.conf import settings
from django.db import models

from accounts.models import MinecraftUser


class GameType(models.IntegerChoices):
  """ Minecraft standard game types """
  SURVIVAL = 0
  CREATIVE = 1


class EnvironmentVar(models.Model):
  """ A stored instance of an ENV_VAR for use with ServerType """
  name = models.CharField(max_length=255)
  value = models.CharField(max_length=255)

  def __str__(self):
    return f'{self.name}={self.value}'


class MineHost(models.Model):
  """
  Represents an instance of a minecraft hosting box,
  where multiple Server() objects may live.
  """
  name = models.CharField(max_length=255, unique=True)
  enabled = models.BooleanField(default=True)
  server_limit = models.IntegerField(default=7)
  min_port = models.IntegerField(default=25565)
  max_port = models.IntegerField(default=25693)

  def __str__(self):
    return f'{self.name}'


class ServerType(models.Model):
  """
  The type of server, and related attributtes.
  """
  name = models.CharField(max_length=255)
  enabled = models.BooleanField(default=True)
  version = models.CharField(default='', max_length=255)
  docker_image = models.CharField(max_length=255)
  environment_vars = models.ManyToManyField(EnvironmentVar, blank=True)

  class Meta:
    unique_together = ('name', 'version')

  def __str__(self):
    return f'{self.name} ({self.version})'


class Server(models.Model):
  """
  Our server object, this represents an instance of a
  minecraft server that contains all the attributes
  needed to launch this server instance.
  """
  name = models.SlugField(max_length=32, unique=True)
  host = models.ForeignKey(MineHost, on_delete=models.CASCADE)
  op_list = models.ManyToManyField(MinecraftUser, blank=True)
  owner = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE
  )
  game_type = models.IntegerField(
    choices=GameType.choices,
    default=GameType.SURVIVAL
  )
  # ServerType(id=1) is a default 'Vanilla' added by migration 0001
  server_type = models.ForeignKey(
    ServerType,
    on_delete=models.CASCADE,
    default=1
  )
  port = models.IntegerField(
    blank=True,
    null=True,
  )

  class Meta:
    unique_together = ('host', 'port')

  def __str__(self):
    return f'{self.name} ({self.host.name}:{self.port})'

  def save(self, force_insert=False, force_update=False, using=None,
    update_fields=None):
    """
    If this is our first time saving the record,
    set the port to the next available value
    in the host's min_port to max_port range.
    This can be overwritten if port is specified
    in the Server object when you create it.
    """
    if not self.pk and not self.port:
      port_list = list(
        self.__class__.objects.filter(host=self.host)
        .values_list('port', flat=True)
      )
      self.port = next(
        p for p in range(self.host.min_port, self.host.max_port) if p not in port_list
      )

    super().save()

  def get_socket(self):
    """ return just the host:port socket URI """
    return f'{self.host.name}:{self.port}'

wrangler/forms.py
"""
file: wrangler/forms.py
author: lkmhaqer
"""
from django.db.models import Count, F
from django.forms import ModelForm, ModelMultipleChoiceField, ModelChoiceField

from accounts.models import MinecraftUser

from .models import MineHost, ServerType, Server


class ServerForm(ModelForm):
  """ The form for users to interface with the server object. """
  class Meta:
    model = Server
    fields = ['name', 'host', 'game_type', 'server_type', 'op_list']

  def __init__(self, *args, **kwargs):
    self.user = kwargs.pop('user', None)
    super(ServerForm, self).__init__(*args, **kwargs) # pylint: disable=R1725

    # For the host field, we want to locate all hosts that have less servers
    # than their self-defined server_limit.
    self.fields['host'] = ModelChoiceField(
      queryset=MineHost.objects.annotate(
          server_count=Count('server')
        ).filter(server_count__lt=F('server_limit'), enabled=True),
      required=True,
    )
    self.fields['server_type'] = ModelChoiceField(
      queryset=ServerType.objects.filter(enabled=True).order_by('name'),
      required=True,
    )
    self.fields['op_list'] = ModelMultipleChoiceField(
      queryset=MinecraftUser.objects.filter(owner=self.user),
      required=False,
    )

  def clean(self):
    if self.user.server_set.count() >= self.user.server_limit:
      self.add_error(
        None,
        f'You are only allowed {self.user.server_limit} servers.'
      )

  def save(self, commit=True):
    server = super(ServerForm, self).save(commit=False) # pylint: disable=R1725
    server.owner = self.user
    if commit:
      server.save()
      self.save_m2m()

    return server

wrangler/views.py
"""
file: wrangler/views.py
author: lkmhaqer
"""
from django.http import Http404, HttpResponseRedirect
from django.core.exceptions import PermissionDenied
from django.template import TemplateDoesNotExist
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import get_object_or_404, render

from accounts.models import User

from .forms import ServerForm
from .models import Server
from .tasks import (
  docker_delete_server,
  docker_restart_server,
  docker_start_server,
  docker_get_logs,
  minecraft_status
)


def index(request):
  """ our root page response """
  return render(request, 'wrangler/index.html')

@login_required
def page(request, template):
  """ Return a given template page where no context is needed. """
  try:
    response = render(request, f'wrangler/{template}.html')
  except TemplateDoesNotExist as err:
    raise Http404 from err
  return response

@login_required
def server_create(request):
  """ Create a Server """
  if request.method == 'POST':
    form = ServerForm(request.POST, user=request.user)
    if form.is_valid():
      server = form.save()
      server = form.instance
      docker_start_server(server)
      return HttpResponseRedirect(reverse('wrangler:server_detail', args=[server.name]))

  else:
    form = ServerForm(user=request.user)

  return render(request, 'wrangler/server_create.html', {'form': form})

@login_required
def server_delete(request, server_name):
  """ Delete a Server """
  if request.method == 'POST':
    server = get_object_or_404(Server, name=server_name)
    if not request.user == server.owner:
      raise PermissionDenied
    docker_delete_server(server)
    server.delete()

  return HttpResponseRedirect(reverse(
    'wrangler:user_status', args=[request.user.username]
  ))

@login_required
def server_restart(request, server_name):
  """ Restart a server """
  if request.method == 'POST':
    server = get_object_or_404(Server, name=server_name)
    if not request.user == server.owner:
      raise PermissionDenied
    docker_restart_server(server)

  return HttpResponseRedirect(reverse(
    'wrangler:user_status', args=[request.user.username]
  ))

@login_required
def server_detail(request, server_name):
  """ Show the details for a server. """
  server = get_object_or_404(Server, name=server_name)
  query = minecraft_status([server])
  query_info, server_status = query['serverlist'][0]

  safe_logs = []
  if request.user == server.owner:
    logs = docker_get_logs(server)
    logs = logs.splitlines()
    safe_logs = [l.decode('utf-8') for l in logs]

  context = {
    'server': server,
    'logs': safe_logs,
    'status': server_status,
    'query_info': query_info
  }

  return render(request, 'wrangler/server_detail.html', context)

def status(request, username=None):
  """ list out servers and show status. """
  if username:
    user = get_object_or_404(User, username=username)
    if not request.user == user:
      raise PermissionDenied
    server_list = Server.objects.filter(owner=user.id)
    template = 'user_status'
  else:
    server_list = Server.objects.all()
    template = 'status'

  servers = minecraft_status(server_list)
  context = {
    'servers': servers['serverlist'],
    'total_players': servers['total_players'],
    'total_capacity': servers['total_capacity']
  }

  return render(request, f'wrangler/{template}.html', context)

wrangler/templates/wrangler/base.html
{% load bootstrap4 %}

<html>
  <head>
    <title>{% block title %}Phukish Minecraft{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>
  <body>
    <div class="container-fluid d-flex h-100 flex-column">
      <div class="row align-items-center">
        <div class="col">
          <h1>Phukish Minecraft</h1>
        </div>
        <div class="col">
            &nbsp;
        </div>
      </div>
      <div class="row">
        <div class="col">
          <ul class="nav nav-tabs">
            {% with url_name=request.resolver_match.url_name %}
            <li class="nav-item">
              <a class="nav-link{% if url_name == 'index' %} active{% endif %}" href="{% url 'wrangler:index' %}">Index</a>
            </li>
            {% endwith %}
            <li class="nav-item">
              <a class="nav-link{% block allserver_active %}{% endblock %}" href="{% url 'wrangler:status' %}">All Servers</a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link{% block myserver_active %}{% endblock %}" href="{% url 'wrangler:user_status' request.user %}">My Servers</a>
              </li>
              {% with url_name=request.resolver_match.url_name %}
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'server_create' %} active{% endif %}" href="{% url 'wrangler:server_create' %}">Create Server</a>
              </li>
              {% endwith %}
              <li class="nav-item">
                <a class="nav-link{% block profile_active %}{% endblock %}" href="{% url 'accounts:user_detail' %}">Profile</a>
              </li>
              {% if user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin Panel</a>
                </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link{% block register_active %}{% endblock %}" href="{% url 'accounts:user_registration' %}">Sign Up</a>
              </li>
              {% with url_name=request.resolver_match.url_name %}
              <li class="nav-item">
                <a class="nav-link{% if url_name == 'login' %} active{% endif %}" href="{% url 'login' %}">Login</a>
              </li>
              {% endwith %}
            {% endif %}
          </ul>
        </div>
      </div>
      <div class="row flex-grow-1">
        <div class="col">
          {% block content %}
    
          <!-- content goes here -->
      
          {% endblock %}
        </div>
      </div>
      <div class="row">
        <div class="col">
          ଘ(੭*ˊᵕˋ)੭* ̀ˋꜱʟᴏᴛʜʟᴏɢɪꜱᴛɪᴄꜱ {{ VERSION }}-{{ BRANCH }}
          <small>
          <span style="color:lightgrey">served from {{ SERVER_NAME }}</span>
          </small>
        </div>
      </div>
    </div>
  </body>
</html>

wrangler/templates/wrangler/guide.html
{% extends 'wrangler/base.html' %}

{% block content %}
<h2>Guide to creating a server</h2>
<ul>
<li>Go to <b>Profile</b> > <b>Add Minecraft User</b></li>
<li>Add your minecraft username, and any user you want to OP or add to an allow-list</li>
<li>Use the <b>Create Server</b> tab</li>
<ul>
  <li><b>Name</b>: A unique server name, can contain letters, numbers and hypens.</li>
  <li><b>Host</b>: The linux computer where your server will live.</li>
  <li>
    <b>Game Type</b>:
    Creative is a free play environment, Survivial is competitive PvE game.
  </li>
  <li><b>Server Type</b>: Vanilla, FeedTheBeast, Forge, pick your mine flavor.</li>
    <ul><li><small><b>Note:</b>The version number on modded types is the modpack version.</small></li></ul>
  <li>
    <b>Op List</b>:
    Select multiple names (added in your profile) to have op power on the server
  </li>
</ul>
<li>Click <b>Create Server</b></li>
<li>You will be taken to the server detail page.</li>
<li>Refresh this page until you see the "server started" text at the bottom of the log.</li>
<li>Vanilla servers take about 60 seconds to boot, Modded servers are 5 to 10 minutes.</li>
</li>
</ul>
{% endblock %}

wrangler/templates/wrangler/index.html
{% extends 'wrangler/base.html' %}
{% load static %}

{% block content %}
<h2>Welcome {{ user.username|default:'Guest' }}</h2>
Today on offer, we have free minecraft servers!<br />
<img src="{% static 'wrangler/spin-diamond-tiny.gif' %}" />
<img src="{% static 'wrangler/spin-diamond-tiny.gif' %}" />
<img src="{% static 'wrangler/spin-diamond-tiny.gif' %}" />
{% endblock %}

wrangler/templates/wrangler/server_create.html
{% extends 'wrangler/base.html' %}
{% load bootstrap4 %}

{% block title %}Create Server - Phukish Minecraft{% endblock %}

{% block content %}
<h2>Create Server</h2>
<p>
  Check out the getting started 
  <a href="{% url 'wrangler:page' 'guide' %}">guide</a>.
</p>
{% if error_message %}<hr><b>{{ error_message }}</b><hr>{% endif %}
<div class="row">
  <div class="col-lg-4">
    <form action="{% url 'wrangler:server_create' %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
        Create Server
        </button>
      {% endbuttons %}
    </form>
  </div>
</div>
{% endblock %}

wrangler/templates/wrangler/server_detail.html
{% extends 'wrangler/base.html' %}

{% block title %}{{ server.name }} Detail - Phukish Minecraft{% endblock %}


{% block myserver_active %}
{% if user == server.owner %} active{% endif %}
{% endblock %}

{% block allserver_active %}
{% if user != server.owner %} active{% endif %}
{% endblock %}

{% block content %}
<b>Name:</b> {{ server.name }}<br />
<b>Host:</b> {{ server.get_socket }}<br />
<b>Type:</b> {{ server.server_type }}<br />
{% if status.version.name %}
<b>Players:</b> {{ status.players.online }} / {{ status.players.max }}<br />
{% endif %}
{% if status.players.online %}
  <p>
  &nbsp;<br />
  {% for player in status.players.sample %}
    <img src="https://minotar.net/avatar/{{ player.id }}/60" />
    {{ player.name }}<br />
  {% endfor %}
  </p>
{% endif %}
{% if logs %}
  <b>Logs:</b>
  <pre><code>
  {% for log in logs %}{{ log }}
  {% endfor %}
{% endif %}
</code></pre>
{% endblock %}

wrangler/templates/wrangler/status.html
{% extends 'wrangler/base.html' %}

{% block title %}Status - Phukish Minecraft{% endblock %}

{% block allserver_active %} active{% endblock %}

{% block content %}

{% if servers %}
<table border=1 cellpadding=5>
  <tr>
    <th>Name</th>
    <th>Host</th>
    <th>Type</th>
    <th>Minecraft Version</th>
    <th>Players</th>
  </tr>
  {% for server, status in servers %}
    {% if status.version.name %}
      <tr class="table-success">
        <td>
          <b><a href="{% url 'wrangler:server_detail' server_name=server.name %}">{{ server.name }}</a></b>
        </td>
        <td>
          {{ server.get_socket }}
        </td>
        <td>
          {{ server.server_type }}
        </td>  
        <td>
          {{ status.version.name }}
        </td>
        <td>
          {{ status.players.online }} / {{ status.players.max }}
        </td>
      </tr>
    {% else %}
      <tr class="table-warning">
        <td>
          <b><a href="{% url 'wrangler:server_detail' server_name=server.name %}">{{ server.name }}</a></b>
        </td>
        <td>
          {{ server.get_socket }}
        </td>
        <td>
          {{ status.version.error }}
        </td>
        <td>
          &nbsp;
        </td>
        <td>
          (╯°□°)╯︵ ┻━┻
        </td>
      </tr>
    {% endif %}
  {% endfor %}
</table>
&nbsp;<br />
Total network-wide players: &nbsp;&nbsp;{{ total_players }} / {{ total_capacity }}
{% else %}
No servers found ¯\_(ツ)_/¯
{% endif %}

{% endblock %}

wrangler/templates/wrangler/user_status.html
{% extends 'wrangler/base.html' %}

{% block title %}User Status - Phukish Minecraft{% endblock %}

{% block myserver_active %} active{% endblock %}

{% block content %}

{% if servers %}
<table border=1 cellpadding=5>
  <tr>
    <th>Name</th>
    <th>Host</th>
    <th>Type</th>
    <th>Minecraft Version</th>
    <th>Players</th>
    <th>Restart</th>
    <th>Delete</th>
  </tr>
  {% for server, status in servers %}
    {% if status.version.name %}
      <tr class="table-success">
        <td>
          <b><a href="{% url 'wrangler:server_detail' server_name=server.name %}">{{ server.name }}</a></b>
        </td>
        <td>
          {{ server.get_socket }}
        </td>
        <td>
          {{ server.server_type }}
        </td>
        <td>
          {{ status.version.name }}
        </td>
        <td>
          {{ status.players.online }} / {{ status.players.max }}
        </td>
        <td>
          <form action="{% url 'wrangler:server_restart' server_name=server.name %}" method="POST" onsubmit="window.confirm_form()">
            {% csrf_token %}
            <input type="submit" value="Restart" />
          </form>
        </td>
        <td>
          <form action="{% url 'wrangler:server_delete' server_name=server.name %}" method="POST" onsubmit="window.confirm_form()">
            {% csrf_token %}
            <input type="submit" value="Delete" />
          </form>
        </td>
      </tr>
    {% else %}
      <tr class="table-warning">
        <td>
          <b><a href="{% url 'wrangler:server_detail' server_name=server.name %}">{{ server.name }}</a></b>
        </td>
        <td>
          {{ server.get_socket }}
        </td>
        <td>
          {{ status.version.error }}
        </td>
        <td>
          &nbsp;
        </td>
        <td>
          (╯°□°)╯︵ ┻━┻
        </td>
        <td>
          <form action="{% url 'wrangler:server_restart' server_name=server.name %}" method="POST" onsubmit="window.confirm_form()">
            {% csrf_token %}
            <input type="submit" value="Restart" disabled />
          </form>
        </td>
        <td>
          <form action="{% url 'wrangler:server_delete' server_name=server.name %}" method="POST" onsubmit="window.confirm_form()">
            {% csrf_token %}
            <input type="submit" value="Delete" />
          </form>
        </td>
      </tr>
    {% endif %}
  {% endfor %}
</table>
&nbsp;<br />
Total players on your servers: &nbsp;&nbsp;{{ total_players }} / {{ total_capacity }}
<script type="text/javascript">
  window.confirm_form = function() {
    var isValid = confirm('Are you sure you?');
    if (!isValid) {
      event.preventDefault();
    }
  }
</script>
{% else %}
No servers found ¯\_(ツ)_/¯
{% endif %}

{% endblock %}