accounts/urls.py
"""
file: accounts/urls.py
author: lkmhaqer
"""
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
  path('detail', views.user_detail, name='user_detail'),
  path('register', views.user_registration, name='user_registration'),
  path(
    'register/<uuid:invite_token>',
    views.user_registration,
    name='invite_registration'
  ),
  path(
    'add_minecraft_user',
    views.add_minecraft_user,
    name='add_minecraft_user'
  ),
]

diamondserv/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('', include('wrangler.urls')),
  path('accounts/', include('django.contrib.auth.urls')),
  path('accounts/', include('accounts.urls')),
  path('admin/', admin.site.urls),
]

accounts/models.py
"""
file: accounts/models.py
author: lkmhaqer
"""
import uuid

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
  """
  Custom user model as suggested by the Django documentation.
  https://docs.djangoproject.com/en/3.1/topics/auth/customizing/
  """
  email = models.EmailField(default='', unique=True)
  server_limit = models.IntegerField(default=2)


class MinecraftUser(models.Model):
  """ A minecraft username, tied to an account. """
  name = models.CharField(max_length=16)
  owner = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE
  )

  def __str__(self):
    return f'{self.name}'


class InviteCode(models.Model):
  """ A one-time use invite code in UUID form. """
  email = models.EmailField(unique=True)
  token = models.UUIDField(default=uuid.uuid4, editable=False)
  used = models.BooleanField(default=False)

  def __str__(self):
    if self.used:
      return f'{self.email} (Used)'
    reg_url = reverse(
      'accounts:invite_registration',
      kwargs={'invite_token': self.token}
    )
    return f'https://mc.phukish.com{reg_url}'

accounts/forms.py
"""
file: wrangler/forms.py
author: lkmhaqer
"""
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm, UUIDField

from .models import InviteCode, MinecraftUser, User


class MinecraftUserForm(ModelForm):
  """ The form for users to add minecraft usernames to their profile. """
  class Meta:
    model = MinecraftUser
    fields = ['name']

  def __init__(self, *args, **kwargs):
    self.user = kwargs.pop('user', None)
    super(MinecraftUserForm, self).__init__(*args, **kwargs) # pylint: disable=R1725

  def save(self, commit=True):
    minecraft_name = super(MinecraftUserForm, self).save(commit=False) # pylint: disable=R1725
    minecraft_name.owner = self.user
    if commit:
      minecraft_name.save()

    return minecraft_name


class UserRegistrationForm(UserCreationForm):
  """ Regular form for users to register with. """
  def clean(self):
    username = self.cleaned_data['username']
    if User.objects.filter(username=username).exists():
      self.add_error('username', 'This username is already taken.')
    email = self.cleaned_data['email']
    if User.objects.filter(email=email).exists():
      self.add_error('email', 'This email has been used already.')

  class Meta(UserCreationForm):
    model = User
    fields = ['username', 'email']


class InviteUserRegistrationForm(UserRegistrationForm):
  """ Registration form with an invite code that must be checked. """
  invite_token = UUIDField()

  def __init__(self, *args, **kwargs): # pylint: disable=W0231
    self.invite = None
    super(InviteUserRegistrationForm, self).__init__(*args, **kwargs) # pylint: disable=R1725

  def clean(self):
    try:
      self.invite = InviteCode.objects.get(
        token=self.cleaned_data['invite_token'],
        used=False
        )
    except (InviteCode.DoesNotExist, KeyError):
      self.add_error('invite_token', 'Invite code not found.')
    username = self.cleaned_data['username']
    if User.objects.filter(username=username).exists():
      self.add_error('username', 'This username is already taken.')
    if 'email' in self.cleaned_data:
      email = self.cleaned_data['email']
      if User.objects.filter(email=email).exists():
        self.add_error('email', 'This email has been used already.')
    else:
      self.add_error('email', 'A valid email address is required.')

  def save(self, commit=True):
    self.invite.used = True
    self.invite.save()
    return super(InviteUserRegistrationForm, self).save(commit=True) # pylint: disable=R1725

  class Meta(UserRegistrationForm.Meta):
    model = User
    

accounts/views.py
"""
file: accounts/views.py
author: lkmhaqer
"""
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .forms import InviteUserRegistrationForm, MinecraftUserForm, UserRegistrationForm
from .models import User


def _get_registration_form(post=None, invite_token=None):
  """ get the current registration form based on invite settings. """
  if settings.INVITE_ONLY:
    return InviteUserRegistrationForm(post, initial={'invite_token': f'{invite_token}'})
  return UserRegistrationForm(post)

def user_registration(request, invite_token=None):
  """ User registration view  """
  if settings.INVITE_ONLY and invite_token is None:
    return render(request, 'accounts/registration_closed.html')

  if request.method == 'POST':
    form = _get_registration_form(request.POST)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(reverse('login'))
  else:
    form = _get_registration_form(post=None, invite_token=invite_token)

  return render(request, 'accounts/registration.html', {'form': form})

@login_required
def add_minecraft_user(request):
  """ Create a Server """
  if request.method == 'POST':
    form = MinecraftUserForm(request.POST, user=request.user)
    if form.is_valid():
      form.save()
      return HttpResponseRedirect(reverse('accounts:user_detail'))

  else:
    form = MinecraftUserForm()

  return render(request, 'accounts/add_minecraft_user.html', {'form': form})

@login_required
def user_detail(request):
  """ Return a profile page for the current logged in user """
  user = get_object_or_404(User, pk=request.user.id)
  return render(request, 'accounts/detail.html', {'user': user})

accounts/templates/accounts/add_minecraft_user.html
{% extends 'registration/form.html' %}

{% block title %}Add Minecraft Username - Phukish Minecraft{% endblock %}

{% block profile_active %} active{% endblock %}

{% block form_name %}Add Minecraft Username{% endblock %}

{% block form_button %}Add{% endblock %}

accounts/templates/accounts/detail.html
{% extends 'wrangler/base.html' %}

{% block title %}User Profile - Phukish Minecraft{% endblock %}

{% block profile_active %} active{% endblock %}

{% block content %}
<p>
<h3>{{ user }}'s Profile</h3>
</p>
<p>
<a href="{% url 'password_change' %}" class="btn btn-primary">Change Password</a>
<a href="{% url 'accounts:add_minecraft_user' %}" class="btn btn-primary">Add Minecraft User</a>
</p>

<p>Minecraft Usernames:
<ul>
{% for minecraft_user in user.minecraftuser_set.all %}
  <li>{{ minecraft_user }}</li>
{% endfor %}
</ul>
</p>
{% endblock %}

accounts/templates/accounts/registration.html
{% extends 'registration/form.html' %}

{% block title %}Registration - Phukish Minecraft{% endblock %}

{% block register_active %} active{% endblock %}

{% block form_name %}Registration{% endblock %}

{% block form_button %}Sign-up{% endblock %}

accounts/templates/accounts/registration_closed.html
{% extends 'wrangler/base.html' %}

{% block title %}Registration - Phukish Minecraft{% endblock %}

{% block register_active %} active{% endblock %}

{% block content %}
<h2>Registration is Invite Only</h2>
<p>Unfortunately we are not accepting new registrations without invite codes at this time.</p>
<p>
  Do you have an invite code to use?
  <a href="{% url 'accounts:invite_registration' '00000000-0000-0000-0000-000000000000' %}">Click Here</a>.
</p>
{% endblock %}